### ISSUE TITLE
Question about recompiling sprite database

### ISSUE THREAD

**Issue by srfoster** [jeapostrophe/mode-lambda#18]
Theoretically speaking, should it be possible to compile a database of known sprites before I begin drawing, and then to recompile it later whenever new sprites become known?  (I'm thinking of a use-case where sprites are procedurally generated during the runtime of a game.)

I know there would be a drawing performance hit on the recompile.  But aside from that, should it work?

I'm having trouble getting it to work -- but I was curious if it *should* work in theory.  Knowing this would help me figure out if I'm just doing something silly in my code or if I'm just doing something fundamentally silly.

**Comment by srfoster** [comment]
I was doing something silly.  The answer would appear to be yes. :)

**Comment by jeapostrophe** [comment]
`mode-lambda` doesn't support this, but it "easily" could. I even have a comment in the code about where you would do it. "All" we need to do is have this `let` block return an extra value that re-runs the highlighted code with a new `csd` provided in an argument. We could then provide an optional argument to the drawing code (like #:r #:g #:b) and get a new one.

However, as you mention this will increase the memory bandwidth, but I doubt it would be very severe. I assume that the only problem would be that the Racket code to generate the atlas is too slow to run at 60Hz.

For your scenario of procedural generation, you could have a set of sprite components and then assemble and overlay them procedurally, which would not require this feature.

https://github.com/jeapostrophe/mode-lambda/blob/master/mode-lambda/backend/gl.rkt#L88-L102
