### ISSUE TITLE
Weird interaction with racket-chipmunk

### ISSUE THREAD

**Issue by srfoster** [jeapostrophe/mode-lambda#19]
Hi, I've switched my budding 2d `game-engine` (https://github.com/thoughtstem/game-engine) to use `mode-lambda` for rendering.  It's great, and way faster now.  I'm really excited about it.

But... (deja vu) I'm getting a bug on Linux that is reminiscent of an issue we dealt with in `lux`:

https://github.com/jeapostrophe/lux/issues/9

Just as a reminder, when `game-engine` runs these lines (in my `racket-chipmunk`) library...

```
(require ffi/unsafe)
(define chipmunk (ffi-lib "./binaries/libchipmunk"))
```

...I immediately got errors when requiring `math/flonum`.  And there was the especially strange (to me) property that these error persisted across all tabs of DrRacket from that moment forward.  The whole Racket process seemed to be "poisoned" in some subtle way.  Maybe that kind of bug is normal with `ffi/unsafe`, but if so, it's beyond my Racket knowledge to even begin to debug it.  (I was grateful that you switched to `racket/math`, which fixed the problem.)

Now, with `mode-lambda` the situation is eerily similar.  The moment Racket does those `racket-chipmunk` lines above, any `mode-lambda` stuff (including the `mode-lambda` examples) all render as solid black.  All DrRacket tabs are affected from the moment those lines run.  There's no error message -- just the usual `mode-lambda`/`lux` window, with healthy FPS numbers on the top bar, everything looking normal... except there is only blackness in the rendering area.

Again, this is a Linux-specific thing.  Indeed, it even seems to affect only a some of my Linux computers.  (But I have a few hundred of those computers, so it's still kind of a big deal for me.)

Anyway, I'm going to cross-post about this on the Racket mailing list since this is the third time this mysterious issue has interfered with me integrating other peoples' cool Racket libraries into `game-engine`.  First it was `rsound`.  Then it was `lux`.  Now `mode-lambda`.  It's probably my fault somehow: the `racket-chipmunk` library certainly seems to be the culprit.  But I'll probably need the community's help on this one.

I wanted to post about it here too, though.  Maybe you have some ideas for further debugging in the context of `mode-lambda`?  Or maybe you have ideas for another workaround (as you did with `lux`)?

**Comment by jeapostrophe** [comment]
I don't really have any idea. My best guess is that libchipmunk sets some global C-level state that messes with Racket's expectations about how the world works.

**Comment by srfoster** [comment]
I'm closing this.  I still don't know the original cause.  But current builds of racket-chipmunk are working fine.
