### ISSUE TITLE
Long load times with the updated text-renderer

### ISSUE THREAD

**Issue by aBlender** [jeapostrophe/mode-lambda#21]
I'm noticing much longer load times in our game-engine with the updated text-renderer

Is there a reason the default `#:scaling` is set to **8.0** in:
[mode-lambda/text/static.rkt](https://github.com/jeapostrophe/mode-lambda/commit/a8c2a3a4eb03f26be630caa9ababfe3128a1dd59#diff-5f8489d770383188626397bfbf9af069)

It's not a big issue, since I can pass in either **1.0** or `(get-display-backing-scale)`. 
**8.0** just seems very high even for a Retina Display.

**Comment by jeapostrophe** [comment]
I think we should change the default to `(* 2.0 (get-display-backing-scale))`. I was talking to Butterick, who gave me a low down on getting better font display and he suggested it. Is that terrible for you?

**Comment by aBlender** [comment]
`(* 2.0 (get-display-backing-scale))` works for us. The load times are much better although I can't tell much improvement in a scaling that is higher then the `display-backing-scale`. Is the goal to get some extra smoothing via supersampling? I'm actually noticing slightly more jaggies at 2x backing scale.

I don't have a Retina display to test, but I set my windows machine display scale to 150%.

Below are screenshots of a 480 by 360 game scaled up (using mode-lambda) by 1.5 (the backing scale).

Size 13 Consolas font, **1x the backing scale**, smoothing off:
![text-at-1x-backing-scale-1-no-smoothing](https://user-images.githubusercontent.com/10148840/63971878-6a41a600-ca5c-11e9-8e03-6d2616fa1053.png)

Size 13 Consolas font, **2x the backing scale**, smoothing off:
![text-at-2x-backing-scale-1-no-smoothing](https://user-images.githubusercontent.com/10148840/63972385-7d08aa80-ca5d-11e9-86d7-637f6d70c5d5.png)

Size 14 Consolas font, **1x backing scale**, smoothing on, mode-7 layer:
![text-at-1x-backing-scale-3](https://user-images.githubusercontent.com/10148840/63973038-c1e11100-ca5e-11e9-8045-ed251ea0da07.png)

**Comment by jeapostrophe** [comment]
Thanks for the experiment. I've switched to just `(get-display-backing-scale)`. It looks pretty nice to me too.
