### ISSUE TITLE
Text display in one.rkt not quite right

### ISSUE THREAD

**Issue by tonyg** [jeapostrophe/mode-lambda#4]
Having repaired #1 and #2, I get good-looking output for many of the options in `one.rkt`. A standout case is the "text" option, however, which gives me the attached output.

![screenshot from 2016-10-07 20-06-33](https://cloud.githubusercontent.com/assets/17710/19208566/b740dada-8cc9-11e6-8931-0519c1bf5df8.png)

**Comment by jeapostrophe** [comment]
That actually does look right. It picks a bunch of weird random characters. It also selects them from a default modern font that doesn't always look neat when you don't have "Triplicate T4c", which is the font of choice for elite Racketeers ;)
